# Generated by Django 5.2.14 on 2026-05-26 06:32

from django.db import migrations


def add_default_tags(apps, schema_editor):
    Tag = apps.get_model('ideaboard', 'Tag')
    tags = ['python', 'django', 'frontend', 'backend', 'android', 'ios', 'machine learning',
             'data science', 'devops', 'game development', 'blockchain', 'cybersecurity', 'cloud computing',
             'artificial intelligence', 'virtual reality', 'augmented reality', 'internet of things', 'big data', 'analytics', 'automation', 'robotics', 'natural language processing', 'computer vision', 'deep learning', 'neural networks',
             'quantum computing',]
    Tag.objects.bulk_create(
        [Tag(name=t.lower().strip()) for t in tags],
        ignore_conflicts=True
    )

class Migration(migrations.Migration):

    dependencies = [
        ('ideaboard', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RunPython(add_default_tags, reverse_code=migrations.RunPython.noop),
    ]
