# Generated by Django 5.2.14 on 2026-05-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideaboard', '0003_auto_20260526_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='cover_imgage_URL',
            new_name='cover_image_URL',
        ),
    ]
